// <auto-generated />
using System;
***REMOVED***
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TypTop.Database;

***REMOVED***.Migrations
***REMOVED***
    [DbContext(typeof(Context))]
    [Migration("20191127095826_word")]
    partial class word
    ***REMOVED***
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        ***REMOVED***
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TypTop.Database.User", b =>
                ***REMOVED***
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Teacher")
                        .HasColumnType("bit");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("User");
            ***REMOVED***);

            modelBuilder.Entity("TypTop.Database.Word", b =>
                ***REMOVED***
                    b.Property<string>("Letters")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Letters");

                    b.ToTable("Word");
            ***REMOVED***);
#pragma warning restore 612, 618
    ***REMOVED***
***REMOVED***
***REMOVED***
